export const SELECCIONAR_CLIENTE_MAYORISTA = 'SELECCIONAR CLIENTE MAYORISTA'
export const SELECCIONAR_PRODUCTO_MAYORISTA = 'SELECCIONAR PRODUCTO MAYORISTA'
export const CANTIDAD_PRODUCTO = 'CANTIDAD_PRODUCTO'